import { NextRequest, NextResponse } from "next/server";
import { writeFileSync, existsSync, readFileSync } from "fs";
import { join } from "path";

const ENV_PATH = join(process.cwd(), ".env.local");

/**
 * GET /api/setup
 * Returns the current status of which services are configured.
 */
export async function GET() {
  const status = {
    openai: !!process.env.OPENAI_API_KEY,
    resend: !!process.env.RESEND_API_KEY,
    supabase: !!(process.env.NEXT_PUBLIC_SUPABASE_URL && (process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)),
    envFileExists: existsSync(ENV_PATH),
  };

  return NextResponse.json(status);
}

/**
 * POST /api/setup
 * Accepts a JSON body with optional keys and writes them to .env.local
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      openaiKey,
      resendKey,
      fromEmail,
      supabaseUrl,
      supabaseKey,
    } = body as {
      openaiKey?: string;
      resendKey?: string;
      fromEmail?: string;
      supabaseUrl?: string;
      supabaseKey?: string;
    };

    // Build the .env.local content
    const lines: string[] = [
      "# Price Guard - Auto-generated by Setup Wizard",
      `# Generated on ${new Date().toISOString()}`,
      "",
    ];

    if (openaiKey?.trim()) {
      lines.push("# OpenAI Vision OCR");
      lines.push(`OPENAI_API_KEY=${openaiKey.trim()}`);
      lines.push("");
    }

    if (resendKey?.trim()) {
      lines.push("# Resend Email Service");
      lines.push(`RESEND_API_KEY=${resendKey.trim()}`);
      if (fromEmail?.trim()) {
        lines.push(`FROM_EMAIL=${fromEmail.trim()}`);
      }
      lines.push("");
    }

    if (supabaseUrl?.trim() && supabaseKey?.trim()) {
      lines.push("# Supabase Database");
      lines.push(`NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl.trim()}`);
      lines.push(`SUPABASE_SERVICE_ROLE_KEY=${supabaseKey.trim()}`);
      lines.push("");
    }

    const envContent = lines.join("\n");

    // Write the file
    writeFileSync(ENV_PATH, envContent, "utf-8");

    return NextResponse.json({ 
      success: true, 
      message: ".env.local saved successfully. Restart the dev server to apply changes.",
      servicesConfigured: {
        openai: !!openaiKey?.trim(),
        resend: !!resendKey?.trim(),
        supabase: !!(supabaseUrl?.trim() && supabaseKey?.trim()),
      }
    });

  } catch (error: any) {
    console.error("Setup API Error:", error);
    return NextResponse.json({ error: error.message || "Failed to save configuration" }, { status: 500 });
  }
}
